import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import Provider from "@/app/provider";
import verifyDatabaseConnection from "@/lib/prisma";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	try {
		await verifyDatabaseConnection();
	} catch (error) {
		return (
			<html lang="en" suppressHydrationWarning>
				<body
					className={cn(
						"bg-background font-sans antialiased",
						fontSans.variable,
					)}
				>
					<div className="p-8 text-xl h-screen w-full flex items-center justify-center text-white font-bold bg-red-500">
						Failed to connect to the database:
						<br /> {(error as Error).message}
					</div>
				</body>
			</html>
		);
	}

	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body
				className={cn("bg-background font-sans antialiased", fontSans.variable)}
			>
				<Provider>
					{children}
					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
